version: '3.6'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    networks:
      - backend
    expose: 
      - 3000
  
  postgres:
    image: postgres
    environment:         
      POSTGRES_DB: template_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: 
      - postgres:/data/postgres/
    networks:
      - backend
    ports:
      - "5432:5432"
    expose:
      - 5432
  
  redis:
    image: redis
    volumes:
      - redis:/data/redis/
    networks: 
      - backend
    ports:
      - "6379:6379"
    expose:
      - 6379

  nginx:
    image: nginx
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - api
    networks: 
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: charlesguertin@live.ca
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - '80:80'
    expose:
      - 80
    networks:
      - backend
    

networks:
  backend:

volumes:
  postgres:
  redis: